"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.zipFile = exports.zipFolder = exports.unzipFile = exports.JSZip = void 0;
var JSZip = require("jszip");
exports.JSZip = JSZip;
var unzip_1 = require("./unzip");
Object.defineProperty(exports, "unzipFile", { enumerable: true, get: function () { return unzip_1.unzipFile; } });
var zip_1 = require("./zip");
Object.defineProperty(exports, "zipFolder", { enumerable: true, get: function () { return zip_1.zipFolder; } });
Object.defineProperty(exports, "zipFile", { enumerable: true, get: function () { return zip_1.zipFile; } });
